#!/usr/bin/env python3
"""
NQB — Nasdaq-100 Futures  |  Dashboard
Run: python3 app.py  →  http://127.0.0.1:8050
"""

import sys, os
sys.path.insert(0, os.path.dirname(__file__))

import json
from datetime import datetime
from zoneinfo import ZoneInfo

import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import dash
from dash import dcc, html, Input, Output, State, dash_table, callback_context
import dash_bootstrap_components as dbc

import config as cfg
import data as datamod
import indicators
import signals as sig_engine
import liquidity as liq
import sessions as sess_mod
import news as news_mod
import alerts as alert_mod
import journal as journal_mod
import database as db_mod
import analytics as ana_mod
import learning as learn_mod
import ml_model
import paper_trading as pt_mod
import tracker as trk_mod
import market_context as mc_mod
import filters as flt_mod

NY = ZoneInfo("America/New_York")

# ── Dollar conversion ──────────────────────────────────────────────────────────
# 1R = base risk per trade in dollars
BASE_RISK_USD = min(
    cfg.DEFAULT_ACCOUNT_SIZE * cfg.DEFAULT_RISK_PCT / 100,
    cfg.DEFAULT_MAX_LOSS
)

def _usd(r_val, signed=True):
    """Convert R multiple to formatted dollar string."""
    if r_val is None:
        return "—"
    usd = r_val * BASE_RISK_USD
    if signed:
        sign = "+" if usd >= 0 else "−"
        return f"{sign}${abs(usd):,.0f}"
    return f"${abs(usd):,.0f}"

def _usd_val(r_val):
    """Raw dollar value from R."""
    if r_val is None:
        return 0.0
    return r_val * BASE_RISK_USD


# ── Design tokens (match CSS variables) ───────────────────────────────────────
BG_BODY  = "#0d1714"
BG_0     = "oklch(0.16 0.005 250)"
BG_1     = "oklch(0.20 0.006 250)"
BG_2     = "oklch(0.235 0.007 250)"
BG_3     = "oklch(0.275 0.008 250)"
BULL     = "oklch(0.78 0.16 152)"
BEAR     = "oklch(0.68 0.20 25)"
INFO     = "oklch(0.74 0.13 235)"
WARN     = "oklch(0.82 0.14 85)"
TEXT     = "oklch(0.94 0.005 250)"
TEXT2    = "oklch(0.78 0.005 250)"
DIM      = "oklch(0.60 0.005 250)"
MUTED    = "oklch(0.48 0.005 250)"
LINE     = "oklch(0.31 0.01 250)"
LINE_S   = "oklch(0.40 0.012 250)"

TF_LABELS = {"scalp": "5m (Scalp)", "swing": "1H (Swing)", "trend": "1D (Trend)"}

DISCLAIMER_TEXT = (
    "NQB is an educational/research tool only — NOT financial advice. "
    "Signals are generated by technical indicators and have not been validated as "
    "statistically predictive of future price movements. Paper-trade before risking real capital. "
    f"1R = ${BASE_RISK_USD:,.0f} (1% of ${cfg.DEFAULT_ACCOUNT_SIZE:,.0f})"
)

app = dash.Dash(
    __name__,
    external_stylesheets=[],   # no Bootstrap — we use our own CSS
    title="NQB",
    suppress_callback_exceptions=True,
)
app.config.suppress_callback_exceptions = True


# ── Shared helpers ─────────────────────────────────────────────────────────────

def _div(text, **style):
    return html.Div(text, style=style)

def _span(text, **style):
    return html.Span(text, style=style)

def _grade_badge(grade: str):
    cls_map = {"A+": "nqb-grade nqb-grade-ap", "A": "nqb-grade nqb-grade-a",
               "B": "nqb-grade nqb-grade-b",   "C": "nqb-grade nqb-grade-c"}
    return html.Span(grade or "—", className=cls_map.get(grade, "nqb-grade nqb-grade-none"))

def _sig_pill(signal: str):
    cls_map = {
        "STRONG BUY":  "nqb-sig nqb-sig-strong-buy",
        "BUY":         "nqb-sig nqb-sig-buy",
        "NEUTRAL":     "nqb-sig nqb-sig-neutral",
        "SELL":        "nqb-sig nqb-sig-sell",
        "STRONG SELL": "nqb-sig nqb-sig-strong-sell",
    }
    return html.Span(signal, className=cls_map.get(signal, "nqb-sig nqb-sig-neutral"))

def _kpi(label, value, sub=None, tone="", big=False):
    cls = "nqb-kpi" + (f" {tone}" if tone else "") + (" big" if big else "")
    val_cls = "nqb-kpi-value" + (" big" if big else "")
    children = [
        html.Div(label, className="nqb-kpi-label"),
        html.Div(value, className=val_cls),
    ]
    if sub:
        children.append(html.Div(sub, className="nqb-kpi-sub"))
    return html.Div(children, className=cls)

def _panel(title, body, subtitle=None, actions=None):
    head_children = [
        html.Div([
            html.Div(title, className="nqb-panel-title"),
            *([ html.Div(subtitle, className="nqb-panel-sub") ] if subtitle else []),
        ])
    ]
    if actions:
        head_children.append(html.Div(actions, className="nqb-panel-actions"))
    return html.Div([
        html.Div(head_children, className="nqb-panel-head",
                 style={"display": "flex", "justifyContent": "space-between", "alignItems": "flex-start"}),
        html.Div(body, className="nqb-panel-body"),
    ], className="nqb-panel")

def _seg(buttons: list, id_prefix: str):
    """Segmented control made of html.Button elements."""
    return html.Div([
        html.Button(label, id=f"{id_prefix}-{val}", n_clicks=0,
                    className="nqb-seg-btn",
                    **{"data-val": val})
        for val, label in buttons
    ], className="nqb-seg")

def _empty_fig(msg="No data"):
    fig = go.Figure()
    fig.update_layout(
        paper_bgcolor=BG_1, plot_bgcolor=BG_1,
        font=dict(color=DIM),
        annotations=[dict(text=msg, showarrow=False, font=dict(size=13, color=DIM),
                          xref="paper", yref="paper", x=.5, y=.5)],
        margin=dict(l=0, r=0, t=0, b=0),
    )
    return fig


# ── Topbar ─────────────────────────────────────────────────────────────────────

def _topbar():
    return html.Header(className="nqb-topbar", children=[
        # Brand
        html.Div(className="nqb-brand", children=[
            html.Div(className="nqb-brand-mark", children=[
                html.Span(className="nqb-pulse"),
                "NQB",
            ]),
            html.Div(["Nasdaq-100 Futures", html.Br(), "Signal Engine"],
                     className="nqb-brand-sub"),
        ]),
        html.Div(className="nqb-sep"),

        # Price ticker
        html.Div(className="nqb-ticker", children=[
            html.Div("NQ=F", className="nqb-ticker-sym"),
            html.Div(className="nqb-ticker-row", children=[
                html.Span(id="tb-price", className="nqb-ticker-price"),
                html.Span(id="tb-delta", className="nqb-ticker-delta"),
            ]),
        ]),
        html.Div(className="nqb-sep"),

        # Session
        html.Div(className="nqb-topbar-cell", children=[
            html.Div("Session", className="nqb-cell-label"),
            html.Span(id="tb-session"),
        ]),
        html.Div(className="nqb-sep"),

        # NY Time (live clock via interval)
        html.Div(className="nqb-topbar-cell", children=[
            html.Div("NY Time", className="nqb-cell-label"),
            html.Div(id="tb-clock", className="nqb-clock mono"),
        ]),
        html.Div(className="nqb-sep"),

        # Active TF buttons
        html.Div(className="nqb-topbar-cell", children=[
            html.Div("Timeframe", className="nqb-cell-label"),
            html.Div(className="nqb-seg", children=[
                html.Button(lbl, id=f"btn-{key}", n_clicks=0,
                            className="nqb-seg-btn")
                for key, lbl in [("scalp","5m"),("swing","1H"),("trend","1D")]
            ]),
        ]),
        html.Div(className="nqb-sep"),

        # Paper trading toggle
        html.Div(className="nqb-topbar-cell", children=[
            html.Div("Paper Trading", className="nqb-cell-label"),
            html.Button(id="tb-paper-btn", n_clicks=0,
                        children="● OFF", className="nqb-paper-badge off"),
        ]),
    ])


# ── Session strip ──────────────────────────────────────────────────────────────

STRIP_SESSIONS = [
    ("Pre-Market",  4.0,  9.5,  "neutral"),
    ("NY Open",     9.5,  11.0, "bull"),
    ("Lunch Chop", 11.0,  14.0, "warn"),
    ("Power Hour", 15.0,  16.0, "info"),
    ("After Hours",16.0,  18.0, "neutral"),
]
STRIP_SPAN = 18.0 - 4.0   # 14 hours

def _session_strip():
    blocks = []
    for name, start, end, tone in STRIP_SESSIONS:
        left  = (start - 4.0) / STRIP_SPAN * 100
        width = (end - start) / STRIP_SPAN * 100
        blocks.append(html.Div(
            name, className=f"nqb-ss-block {tone}",
            style={"left": f"{left:.1f}%", "width": f"{width:.1f}%"},
        ))
    # Current time marker (static on load; updates via id="ss-now")
    blocks.append(html.Div(id="ss-now", className="nqb-ss-now"))

    axis_labels = [html.Span(f"{h:02d}:00", className="mono dim") for h in [4, 7, 10, 13, 16, 18]]

    return html.Div(className="nqb-session-strip", children=[
        html.Div(blocks, className="nqb-ss-track"),
        html.Div(axis_labels, className="nqb-ss-axis"),
    ])


# ── Dashboard tab layout ───────────────────────────────────────────────────────

def _dashboard_layout():
    return html.Div([
        # ── KPI row ──────────────────────────────────────────────────────────
        html.Div(id="kpi-row", className="nqb-kpi-row"),

        # ── Main body ─────────────────────────────────────────────────────────
        html.Div(style={
            "display": "grid",
            "gridTemplateColumns": "1fr 1fr",
            "gap": "14px",
            "padding": "14px 20px",
        }, children=[
            # Left column: Multi-TF signals
            html.Div(id="mtf-panel"),

            # Right column: market context + trade info + open positions
            html.Div([
                html.Div(id="context-panel", style={"marginBottom": "14px"}),
                html.Div(id="positions-panel"),
            ]),
        ]),

        # ── Full-width chart ──────────────────────────────────────────────────
        html.Div(style={"padding": "0 20px 14px"}, children=[
            _panel("Price Chart", dcc.Graph(
                id="main-chart",
                style={"height": "380px"},
                config={"displayModeBar": False, "scrollZoom": True,
                        "doubleClick": "reset"},
            )),
        ]),

        # ── News warning (full width) ──────────────────────────────────────────
        html.Div(id="news-warning", style={"padding": "0 20px 14px"}),

        dcc.Store(id="active-tf",       data="swing"),
        dcc.Store(id="last-alert-key",  data=""),
        dcc.Store(id="active-mtf-tab",  data="swing"),
        dcc.Interval(id="refresh-timer", interval=60_000, n_intervals=0),
        dcc.Interval(id="clock-timer",   interval=1_000,  n_intervals=0),
    ])


# ── Backtester tab ─────────────────────────────────────────────────────────────

def _backtest_layout():
    return html.Div(style={"padding": "14px 20px"}, children=[
        html.Div(style={"display": "flex", "gap": "12px", "alignItems": "center",
                        "marginBottom": "16px"}, children=[
            html.Span("Timeframe:", style={"color": DIM, "fontSize": "12px"}),
            dcc.Dropdown(
                id="bt-tf-select",
                options=[{"label": v, "value": k} for k, v in TF_LABELS.items()],
                value="swing", clearable=False,
                style={"width": "200px", "backgroundColor": BG_1, "color": TEXT,
                       "border": f"1px solid {LINE}"},
            ),
            html.Button("▶  Run Backtest", id="bt-run-btn", n_clicks=0,
                        className="nqb-btn nqb-btn-primary"),
            html.Span("Approximate — no slippage, commissions, or fill delays.",
                      style={"color": MUTED, "fontSize": "11px"}),
        ]),
        dcc.Loading(type="circle", color=INFO, children=[
            html.Div(id="bt-stats-row", style={"display": "flex", "gap": "8px",
                                                "flexWrap": "wrap", "marginBottom": "16px"}),
            html.Div(id="bt-by-signal", style={"marginBottom": "16px"}),
            dcc.Graph(id="bt-equity-chart", style={"height": "220px", "marginBottom": "16px"},
                      config={"displayModeBar": False}),
            html.Div(id="bt-trade-table"),
        ]),
    ])


# ── Risk calculator tab ────────────────────────────────────────────────────────

def _risk_layout():
    def _inp(label, id_, value, step=1, min_=0, suffix=""):
        return html.Div(style={"marginBottom": "14px"}, children=[
            html.Div(label, style={"fontSize": "10px", "color": MUTED, "textTransform": "uppercase",
                                   "letterSpacing": ".05em", "marginBottom": "4px"}),
            html.Div(style={"display": "flex", "alignItems": "center", "gap": "8px"}, children=[
                dcc.Input(id=id_, type="number", value=value, step=step, min=min_,
                          style={"backgroundColor": BG_2, "color": TEXT,
                                 "border": f"1px solid {LINE}", "borderRadius": "4px",
                                 "padding": "7px 10px", "width": "150px", "fontSize": "14px"}),
                html.Span(suffix, style={"color": DIM, "fontSize": "12px"}),
            ]),
        ])

    return html.Div(style={"maxWidth": "760px", "padding": "14px 20px"}, children=[
        _panel("Position Size Calculator", html.Div([
            html.Div(style={"display": "grid", "gridTemplateColumns": "1fr 1fr", "gap": "0 32px"}, children=[
                html.Div([
                    _inp("Account Size",     "rc-account",  cfg.DEFAULT_ACCOUNT_SIZE, 1000, suffix="USD"),
                    _inp("Risk Per Trade",   "rc-risk-pct", cfg.DEFAULT_RISK_PCT,     0.1,  suffix="%"),
                    _inp("Hard Max Loss",    "rc-max-loss", cfg.DEFAULT_MAX_LOSS,     50,   suffix="USD"),
                    _inp("Entry Price",      "rc-entry",    0,                        0.25, suffix="pts"),
                    _inp("Stop Price",       "rc-stop",     0,                        0.25, suffix="pts"),
                ]),
                html.Div([
                    html.Div(style={"marginBottom": "14px"}, children=[
                        html.Div("Contract Type", style={"fontSize": "10px", "color": MUTED,
                                                          "textTransform": "uppercase",
                                                          "letterSpacing": ".05em", "marginBottom": "4px"}),
                        dcc.RadioItems(id="rc-contract-type",
                            options=[{"label": "  NQ ($20/pt)",  "value": "NQ"},
                                     {"label": "  MNQ ($2/pt)",  "value": "MNQ"}],
                            value="MNQ", inline=True,
                            style={"color": TEXT, "fontSize": "13px", "gap": "20px"}),
                    ]),
                    html.Div([
                        html.Div("Grade", style={"fontSize": "10px", "color": MUTED,
                                                  "textTransform": "uppercase", "letterSpacing": ".05em",
                                                  "marginBottom": "4px"}),
                        html.Div(className="nqb-seg", style={"marginBottom": "14px"}, children=[
                            html.Button(g, id=f"rc-grade-{g.replace('+','p')}", n_clicks=0,
                                        className="nqb-seg-btn")
                            for g in ["A+", "A", "B", "C"]
                        ]),
                    ]),
                    html.Div(id="rc-results"),
                    html.Div(style={
                        "backgroundColor": "oklch(0.20 0.04 85 / .15)",
                        "border": f"1px solid {WARN}", "borderRadius": "6px",
                        "padding": "10px 12px", "marginTop": "14px",
                        "color": WARN, "fontSize": "11px", "lineHeight": "1.7",
                    }, children=[
                        html.Strong("NQ: "), "Tick = 0.25 pts = $5  |  1 pt = $20  |  Margin ≈$18k",
                        html.Br(),
                        html.Strong("MNQ: "), "Tick = 0.25 pts = $0.50  |  1 pt = $2  |  Margin ≈$1.8k",
                    ]),
                ]),
            ]),
        ])),
    ])


# ── Trade journal tab ──────────────────────────────────────────────────────────

def _journal_layout():
    return html.Div(style={"padding": "14px 20px"}, children=[
        html.Div(style={"display": "flex", "gap": "10px", "alignItems": "center",
                        "marginBottom": "14px"}, children=[
            html.Div("Trade Journal", style={"fontSize": "14px", "fontWeight": "600", "color": TEXT}),
            html.Button("↺ Refresh", id="jrn-refresh-btn", n_clicks=0, className="nqb-btn nqb-btn-ghost"),
            html.Button("⬇ Export CSV", id="jrn-export-btn", n_clicks=0, className="nqb-btn nqb-btn-ghost",
                        style={"color": BULL, "borderColor": BULL}),
            dcc.Download(id="jrn-download"),
            html.Span("Edit 'outcome' and 'pnl_pts' directly in the table.",
                      style={"color": MUTED, "fontSize": "11px"}),
        ]),
        html.Div(id="jrn-table-container"),
        dcc.Store(id="jrn-store"),
    ])


# ── Analytics tab ──────────────────────────────────────────────────────────────

def _analytics_layout():
    return html.Div(style={"padding": "14px 20px"}, children=[
        html.Div(style={"display": "flex", "gap": "8px", "alignItems": "center",
                        "marginBottom": "14px", "flexWrap": "wrap"}, children=[
            html.Button("↺ Refresh Analytics",  id="ana-refresh-btn",  n_clicks=0, className="nqb-btn nqb-btn-primary"),
            html.Button("⚙ Run Weight Update",  id="ana-weight-btn",   n_clicks=0, className="nqb-btn nqb-btn-warn"),
            html.Button("🤖 Train ML Model",    id="ana-ml-train-btn", n_clicks=0, className="nqb-btn nqb-btn-ghost"),
            html.Span(id="ana-status", style={"color": DIM, "fontSize": "12px"}),
        ]),
        dcc.Loading(type="circle", color=INFO, children=[
            html.Div(id="ana-summary-row",
                     style={"display": "flex", "gap": "8px", "flexWrap": "wrap", "marginBottom": "16px"}),
            html.Div(style={"display": "grid", "gridTemplateColumns": "1fr 1fr 1fr 1fr",
                             "gap": "14px", "marginBottom": "16px"}, children=[
                html.Div([html.Div("By Timeframe",   style={"fontSize": "10px", "color": MUTED,
                                                              "textTransform": "uppercase",
                                                              "letterSpacing": ".05em", "marginBottom": "6px"}),
                          html.Div(id="ana-tf-table")]),
                html.Div([html.Div("By Session",     style={"fontSize": "10px", "color": MUTED,
                                                              "textTransform": "uppercase",
                                                              "letterSpacing": ".05em", "marginBottom": "6px"}),
                          html.Div(id="ana-sess-table")]),
                html.Div([html.Div("By Grade",       style={"fontSize": "10px", "color": MUTED,
                                                              "textTransform": "uppercase",
                                                              "letterSpacing": ".05em", "marginBottom": "6px"}),
                          html.Div(id="ana-grade-table")]),
                html.Div([html.Div("By Signal Type", style={"fontSize": "10px", "color": MUTED,
                                                              "textTransform": "uppercase",
                                                              "letterSpacing": ".05em", "marginBottom": "6px"}),
                          html.Div(id="ana-sigtype-table")]),
            ]),
            html.Div(style={"display": "grid", "gridTemplateColumns": "1fr 1fr",
                             "gap": "14px", "marginBottom": "16px"}, children=[
                html.Div([html.Div("Best Setups", style={"fontSize": "10px", "color": BULL,
                                                           "textTransform": "uppercase",
                                                           "letterSpacing": ".05em", "marginBottom": "6px"}),
                          html.Div(id="ana-best-table")]),
                html.Div([html.Div("Setups to Avoid", style={"fontSize": "10px", "color": BEAR,
                                                               "textTransform": "uppercase",
                                                               "letterSpacing": ".05em", "marginBottom": "6px"}),
                          html.Div(id="ana-worst-table")]),
            ]),
            html.Div(style={"display": "grid", "gridTemplateColumns": "1fr 1fr",
                             "gap": "14px", "marginBottom": "16px"}, children=[
                html.Div([html.Div("Indicator Contribution", style={"fontSize": "10px", "color": MUTED,
                                                                      "textTransform": "uppercase",
                                                                      "letterSpacing": ".05em", "marginBottom": "6px"}),
                          dcc.Graph(id="ana-weight-chart", style={"height": "240px"},
                                    config={"displayModeBar": False})]),
                html.Div([html.Div("Top Confluence Factors", style={"fontSize": "10px", "color": MUTED,
                                                                      "textTransform": "uppercase",
                                                                      "letterSpacing": ".05em", "marginBottom": "6px"}),
                          html.Div(id="ana-factor-table")]),
            ]),
            html.Div([html.Div("Learned Weight History", style={"fontSize": "10px", "color": MUTED,
                                                                  "textTransform": "uppercase",
                                                                  "letterSpacing": ".05em", "marginBottom": "6px"}),
                      html.Div(id="ana-weight-history")]),
        ]),
    ])


# ── Paper trading tab ──────────────────────────────────────────────────────────

def _paper_layout():
    return html.Div(style={"padding": "14px 20px"}, children=[
        html.Div(style={"display": "flex", "gap": "10px", "alignItems": "center",
                        "marginBottom": "14px", "flexWrap": "wrap"}, children=[
            html.Button(id="pt-toggle-btn", n_clicks=0, children="▶ Enable Paper Trading",
                        className="nqb-btn nqb-btn-primary"),
            html.Button("↺ Refresh", id="pt-refresh-btn", n_clicks=0, className="nqb-btn nqb-btn-ghost"),
            html.Button("📄 Weekly Report", id="pt-report-btn", n_clicks=0,
                        className="nqb-btn nqb-btn-ghost", style={"color": INFO, "borderColor": INFO}),
            html.Span(id="pt-status-badge"),
        ]),
        html.Div(id="pt-summary-row", style={"display": "flex", "gap": "8px",
                                              "flexWrap": "wrap", "marginBottom": "16px"}),
        html.Div(style={"marginBottom": "12px"}, children=[
            html.Div("Open Paper Positions", style={"fontSize": "10px", "color": MUTED,
                                                     "textTransform": "uppercase",
                                                     "letterSpacing": ".05em", "marginBottom": "6px"}),
            html.Div(id="pt-open-table"),
        ]),
        html.Div(style={"marginBottom": "16px"}, children=[
            html.Div("Closed Paper Trades", style={"fontSize": "10px", "color": MUTED,
                                                    "textTransform": "uppercase",
                                                    "letterSpacing": ".05em", "marginBottom": "6px"}),
            html.Div(id="pt-closed-table"),
        ]),
        html.Div(id="pt-report-container", style={"display": "none",
                                                    "backgroundColor": BG_1,
                                                    "border": f"1px solid {LINE}",
                                                    "borderRadius": "6px", "padding": "16px"}),
        dcc.Store(id="pt-enabled", data=False),
        dcc.Interval(id="pt-poll", interval=60_000, n_intervals=0),
    ])


# ── Profitability Report tab ───────────────────────────────────────────────────

def _profit_layout():
    return html.Div(style={"padding": "14px 20px"}, children=[
        html.Div(style={"display": "flex", "gap": "10px", "alignItems": "center",
                        "marginBottom": "14px", "flexWrap": "wrap"}, children=[
            html.Div("Profitability Report", style={"fontSize": "14px", "fontWeight": "600", "color": TEXT}),
            html.Button("↺ Refresh", id="prf-refresh-btn", n_clicks=0, className="nqb-btn nqb-btn-primary"),
            dcc.RadioItems(id="prf-mode",
                options=[{"label": "  All", "value": "all"},
                         {"label": "  Live", "value": "live"},
                         {"label": "  Paper", "value": "paper"}],
                value="all", inline=True,
                style={"color": TEXT, "fontSize": "12px", "gap": "16px"}),
        ]),
        dcc.Loading(type="circle", color=INFO, children=[
            html.Div(id="prf-summary-row", style={"display": "flex", "gap": "8px",
                                                   "flexWrap": "wrap", "marginBottom": "16px"}),
            html.Div(style={"display": "grid", "gridTemplateColumns": "1fr 1fr",
                             "gap": "14px", "marginBottom": "14px"}, children=[
                html.Div([html.Div("Best Sessions", style={"fontSize": "10px", "color": BULL,
                                                            "textTransform": "uppercase",
                                                            "letterSpacing": ".05em", "marginBottom": "6px"}),
                          html.Div(id="prf-best-sess")]),
                html.Div([html.Div("Worst Sessions", style={"fontSize": "10px", "color": BEAR,
                                                             "textTransform": "uppercase",
                                                             "letterSpacing": ".05em", "marginBottom": "6px"}),
                          html.Div(id="prf-worst-sess")]),
            ]),
            html.Div(style={"display": "grid", "gridTemplateColumns": "1fr 1fr",
                             "gap": "14px", "marginBottom": "14px"}, children=[
                html.Div([html.Div("Best Setups", style={"fontSize": "10px", "color": BULL,
                                                          "textTransform": "uppercase",
                                                          "letterSpacing": ".05em", "marginBottom": "6px"}),
                          html.Div(id="prf-best-setup")]),
                html.Div([html.Div("Worst Setups", style={"fontSize": "10px", "color": BEAR,
                                                           "textTransform": "uppercase",
                                                           "letterSpacing": ".05em", "marginBottom": "6px"}),
                          html.Div(id="prf-worst-setup")]),
            ]),
            html.Div(style={"marginBottom": "8px"}, children=[
                html.Div("Expectancy  [ E = (WR × Avg Win $) − (LR × Avg Loss $) ]",
                         style={"fontSize": "11px", "color": MUTED, "marginBottom": "10px"}),
                html.Div(style={"display": "grid", "gridTemplateColumns": "1fr 1fr 1fr 1fr",
                                 "gap": "14px", "marginBottom": "14px"}, children=[
                    html.Div([html.Div("By Session",    style={"fontSize": "10px", "color": MUTED,
                                                                "letterSpacing": ".05em", "marginBottom": "6px"}),
                              html.Div(id="prf-exp-sess")]),
                    html.Div([html.Div("By Timeframe",  style={"fontSize": "10px", "color": MUTED,
                                                                "letterSpacing": ".05em", "marginBottom": "6px"}),
                              html.Div(id="prf-exp-tf")]),
                    html.Div([html.Div("By Grade",      style={"fontSize": "10px", "color": MUTED,
                                                                "letterSpacing": ".05em", "marginBottom": "6px"}),
                              html.Div(id="prf-exp-grade")]),
                    html.Div([html.Div("By Signal Type",style={"fontSize": "10px", "color": MUTED,
                                                                "letterSpacing": ".05em", "marginBottom": "6px"}),
                              html.Div(id="prf-exp-stype")]),
                ]),
            ]),
            html.Div([
                html.Div("Filter Recommendations", style={"fontSize": "10px", "color": WARN,
                                                           "textTransform": "uppercase",
                                                           "letterSpacing": ".05em", "marginBottom": "8px"}),
                html.Div(id="prf-recommendations"),
            ]),
        ]),
    ])


# ── App layout ─────────────────────────────────────────────────────────────────

_tab_s  = {"color": DIM,  "backgroundColor": BG_0, "border": f"1px solid {LINE}",
           "borderRadius": "4px 4px 0 0", "padding": "8px 16px", "fontSize": "12px"}
_tab_a  = {"color": TEXT, "backgroundColor": BG_1, "border": f"1px solid {LINE}",
           "borderBottom": f"2px solid {INFO}", "borderRadius": "4px 4px 0 0",
           "padding": "8px 16px", "fontSize": "12px", "fontWeight": "600"}

app.layout = html.Div(
    style={"backgroundColor": BG_BODY, "minHeight": "100vh",
           "fontFamily": "-apple-system, BlinkMacSystemFont, 'Inter', sans-serif"},
    children=[
        _topbar(),
        _session_strip(),
        dcc.Tabs(
            id="main-tabs", value="tab-dashboard",
            style={"backgroundColor": BG_0, "borderBottom": f"1px solid {LINE}",
                   "padding": "0 20px"},
            colors={"border": LINE, "primary": INFO, "background": BG_0},
            children=[
                dcc.Tab(label="Dashboard",       value="tab-dashboard",   style=_tab_s, selected_style=_tab_a),
                dcc.Tab(label="Backtester",      value="tab-backtest",    style=_tab_s, selected_style=_tab_a),
                dcc.Tab(label="Analytics",       value="tab-analytics",   style=_tab_s, selected_style=_tab_a),
                dcc.Tab(label="Paper Trading",   value="tab-paper",       style=_tab_s, selected_style=_tab_a),
                dcc.Tab(label="Risk Calculator", value="tab-risk",        style=_tab_s, selected_style=_tab_a),
                dcc.Tab(label="Trade Journal",   value="tab-journal",     style=_tab_s, selected_style=_tab_a),
                dcc.Tab(label="Profitability",   value="tab-profit",      style=_tab_s, selected_style=_tab_a),
            ],
        ),
        html.Div(id="tab-content"),
        html.Div([
            DISCLAIMER_TEXT,
        ], className="nqb-footer"),
    ],
)


# ── Tab renderer ───────────────────────────────────────────────────────────────

@app.callback(Output("tab-content", "children"), Input("main-tabs", "value"))
def render_tab(tab):
    if tab == "tab-dashboard":  return _dashboard_layout()
    if tab == "tab-backtest":   return _backtest_layout()
    if tab == "tab-analytics":  return _analytics_layout()
    if tab == "tab-paper":      return _paper_layout()
    if tab == "tab-risk":       return _risk_layout()
    if tab == "tab-journal":    return _journal_layout()
    if tab == "tab-profit":     return _profit_layout()
    return ""


# ── Live clock ─────────────────────────────────────────────────────────────────

@app.callback(
    Output("tb-clock", "children"),
    Output("ss-now",   "style"),
    Input("clock-timer", "n_intervals"),
)
def tick_clock(_):
    now = datetime.now(NY)
    clock = now.strftime("%H:%M:%S")
    h = now.hour + now.minute / 60
    left = max(0.0, min(100.0, (h - 4.0) / STRIP_SPAN * 100))
    style = {"left": f"{left:.1f}%", "position": "absolute", "top": "0",
             "bottom": "0", "width": "2px", "background": "white",
             "opacity": ".6", "transform": "translateX(-50%)"}
    return clock, style


# ── Timeframe buttons ──────────────────────────────────────────────────────────

@app.callback(
    Output("active-tf", "data"),
    [Input(f"btn-{k}", "n_clicks") for k in ["scalp", "swing", "trend"]],
    State("active-tf", "data"),
    prevent_initial_call=True,
)
def set_tf(*args):
    ctx = callback_context
    if not ctx.triggered:
        return args[-1]
    return ctx.triggered[0]["prop_id"].split(".")[0].replace("btn-", "")


# ── Main dashboard refresh ─────────────────────────────────────────────────────

@app.callback(
    [Output("tb-price",       "children"),
     Output("tb-delta",       "className"),
     Output("tb-delta",       "children"),
     Output("tb-session",     "children"),
     Output("kpi-row",        "children"),
     Output("mtf-panel",      "children"),
     Output("context-panel",  "children"),
     Output("positions-panel","children"),
     Output("main-chart",     "figure"),
     Output("news-warning",   "children"),
     Output("last-alert-key", "data")],
    [Input("active-tf",     "data"),
     Input("refresh-timer", "n_intervals")],
    State("last-alert-key", "data"),
)
def refresh(tf_key, _, last_alert_key):
    tf_key = tf_key or "swing"
    tf = cfg.TIMEFRAMES[tf_key]

    df = datamod.fetch(interval=tf["interval"], period=tf["period"])
    if df is None or df.empty:
        return ("—", "nqb-ticker-delta", "", _session_pill_el(),
                [], _empty_panel("No data"), _empty_panel(""), _empty_panel(""),
                _empty_fig("No data — market may be closed"), "", last_alert_key)

    df  = indicators.add_all(df)
    sig = sig_engine.evaluate(df, tf["label"])

    # HTF confirmation
    htf_key = tf.get("htf")
    htf_sig = None
    htf_df  = None
    if htf_key:
        htf_tf = cfg.TIMEFRAMES[htf_key]
        htf_df = datamod.fetch(interval=htf_tf["interval"], period=htf_tf["period"])
        if htf_df is not None and not htf_df.empty:
            htf_df  = indicators.add_all(htf_df)
            htf_sig = sig_engine.evaluate(htf_df, htf_tf["label"])

    sig_engine.add_grade(sig, htf_sig)

    # Market context + filter
    htf_direction = "NEUTRAL"
    if htf_sig:
        if "BUY"  in htf_sig.signal and "NEUTRAL" not in htf_sig.signal: htf_direction = "BULL"
        elif "SELL" in htf_sig.signal and "NEUTRAL" not in htf_sig.signal: htf_direction = "BEAR"

    try:
        context = mc_mod.classify(df, htf_direction)
    except Exception:
        context = None

    try:
        filter_result = flt_mod.evaluate(sig, df, context)
    except Exception:
        filter_result = None

    if filter_result and filter_result.allowed and sig.grade in ("A", "A+"):
        try:
            sig = sig_engine.enhance_signal(sig, df)
        except Exception:
            pass

    # Track open outcomes
    sess = sess_mod.current_session()
    preloaded = {tf_key: df}
    if htf_key and htf_df is not None:
        preloaded[htf_key] = htf_df
    try:
        trk_mod.check_all_open(preloaded=preloaded)
    except Exception:
        pass

    # Log + alert
    alert_key = last_alert_key
    is_tradeable = (sig.grade in ("A", "A+") and "NEUTRAL" not in sig.signal
                    and sig.stop_loss and (filter_result is None or filter_result.allowed))
    if is_tradeable:
        new_key = f"{sig.signal}|{sig.grade}|{tf_key}|{round(sig.price, -1)}"
        if new_key != last_alert_key:
            try: db_mod.log_signal(sig, session=sess["name"], paper=False)
            except Exception: pass
            journal_mod.log_signal(sig)
            if pt_mod.is_enabled():
                try: pt_mod.open_trade(sig, session=sess["name"])
                except Exception: pass
            alert_mod.send_if_notable(sig)
            alert_key = new_key

    # ── Price / change ─────────────────────────────────────────────────────
    price      = sig.price
    prev_close = float(df["close"].iloc[-2]) if len(df) > 1 else price
    chg        = price - prev_close
    chg_pct    = chg / prev_close * 100 if prev_close else 0
    delta_cls  = "nqb-ticker-delta up" if chg >= 0 else "nqb-ticker-delta down"
    delta_txt  = f"{'▲' if chg >= 0 else '▼'} {abs(chg):,.1f}  ({abs(chg_pct):.2f}%)"

    # ── Session pill ───────────────────────────────────────────────────────
    sess_el = _session_pill_el(sess)

    # ── KPI row ────────────────────────────────────────────────────────────
    try:
        trades = db_mod.get_completed_trades()
        stats  = ana_mod.overall_stats(trades)
    except Exception:
        stats  = {}

    net_usd = _usd_val(stats.get("net_r"))
    exp_usd = _usd_val(stats.get("expectancy"))
    dd_usd  = _usd_val(stats.get("max_drawdown_r", 0))
    wr      = stats.get("win_rate", 0)

    kpi_items = [
        _kpi("Net P&L",
             _usd(stats.get("net_r")) if stats else "—",
             sub=f"{stats.get('total',0)} completed trades",
             tone="bull" if net_usd >= 0 else "bear", big=True),
        _kpi("Win Rate",
             f"{wr:.1f}%" if stats else "—",
             sub=f"{stats.get('wins',0)}W / {stats.get('losses',0)}L",
             tone="bull" if wr >= 50 else "bear"),
        _kpi("Profit Factor",
             str(stats.get("profit_factor") or "—"),
             sub="gross profit / gross loss",
             tone="bull" if (stats.get("profit_factor") or 0) >= 1 else "bear"),
        _kpi("Expectancy",
             _usd(stats.get("expectancy")) if stats else "—",
             sub="per trade · 1R = $" + f"{BASE_RISK_USD:,.0f}",
             tone="bull" if exp_usd >= 0 else "bear"),
        _kpi("Max Drawdown",
             _usd(stats.get("max_drawdown_r", 0), signed=False) if stats else "—",
             sub="peak-to-trough", tone="bear"),
        _kpi("Confluence",
             f"{max(sig.bull_score, sig.bear_score):.0f}/100",
             sub=f"{'BUY' if 'BUY' in sig.signal else 'SELL' if 'SELL' in sig.signal else 'NEUTRAL'} · {tf['label']}"),
    ]

    # ── MTF signal panel ───────────────────────────────────────────────────
    mtf_panel_el = _build_mtf_panel(sig, htf_sig, htf_key, tf_key, filter_result, context)

    # ── Context + filter panel ─────────────────────────────────────────────
    ctx_panel_el = _build_context_panel(context, filter_result, sess, sig)

    # ── Open positions ─────────────────────────────────────────────────────
    try:
        open_trades = db_mod.get_open_outcomes()
    except Exception:
        open_trades = []
    pos_panel_el = _build_positions_panel(open_trades)

    # ── News warning ───────────────────────────────────────────────────────
    events = news_mod.get_upcoming_events(hours_ahead=24)
    news_el = ""
    if events:
        news_el = html.Div(className="nqb-no-trade",
                           style={"borderColor": WARN, "color": WARN,
                                  "backgroundColor": "oklch(0.82 0.14 85 / .1)"},
                           children=[
            html.Strong("⚠ High-Impact Events in Next 24H: "),
            ", ".join(f"{e['title']} ({e['date_str']})" for e in events[:3]),
        ])

    fig = _build_chart(df, sig, tf_key)

    return (f"{price:,.2f}", delta_cls, delta_txt, sess_el,
            kpi_items, mtf_panel_el, ctx_panel_el, pos_panel_el,
            fig, news_el, alert_key)


def _session_pill_el(sess=None):
    if sess is None:
        sess = sess_mod.current_session()
    tone = sess.get("color_tone", "neutral")
    # Map hex color to tone
    name = sess.get("name", "")
    if "Open" in name:     tone = "bull"
    elif "Power" in name:  tone = "info"
    elif "Lunch" in name:  tone = "warn"
    else:                  tone = "neutral"
    return html.Span([
        html.Span(className="nqb-session-dot"),
        sess.get("name", "—"),
    ], className=f"nqb-session-pill {tone}")


def _empty_panel(msg):
    return _panel("—", html.Div(msg, style={"color": MUTED, "fontSize": "12px"}))


def _build_mtf_panel(sig, htf_sig, htf_key, tf_key, filter_result, context):
    is_long = "BUY" in sig.signal and "NEUTRAL" not in sig.signal
    is_short = "SELL" in sig.signal and "NEUTRAL" not in sig.signal

    # Tab header for active TF
    tab_color = BULL if is_long else (BEAR if is_short else WARN)

    # Bull/bear bar
    bull_w = f"{sig.bull_score:.1f}%"
    bear_w = f"{sig.bear_score:.1f}%"

    # Signal summary blocks
    atr = sig.atr
    ss_blocks = [
        _ss_block("Price",        f"{sig.price:,.2f}"),
        _ss_block("Signal",       _sig_pill(sig.signal)),
        _ss_block("Grade",        _grade_badge(sig.grade)),
        _ss_block("ATR(14)",      f"{atr:.1f} pts" if atr else "—"),
        _ss_block("R:R",          f"{sig.risk_reward:.2f}×" if sig.risk_reward else "—"),
        _ss_block("HTF",
                  html.Span("✓ confirmed", style={"color": BULL}) if sig.mtf_confirmed
                  else html.Span("✗ conflicts", style={"color": BEAR}) if htf_sig else html.Span("—", style={"color": MUTED})),
        _ss_block("Entry Type",   sig.entry_type or "—"),
        _ss_block("Stop Type",    sig.stop_type or "ATR"),
    ]

    # Trade idea strip
    trade_idea = ""
    if (is_long or is_short) and sig.stop_loss:
        dir_cls    = "long" if is_long else "short"
        dir_label  = "LONG" if is_long else "SHORT"
        risk_usd   = abs(sig.price - sig.stop_loss) * (cfg.MNQ_POINT_VALUE if True else cfg.NQ_POINT_VALUE)

        cells = [
            _ti_cell("Direction", html.Span(dir_label, className=f"nqb-dir {dir_cls}"), ""),
            _ti_cell("Entry", f"{sig.price:,.2f}", ""),
            _ti_cell("Stop", f"{sig.stop_loss:,.2f}", sig.stop_type or "ATR", bear=True),
        ]
        if sig.partial_tp1 > 0:
            cells.append(_ti_cell("TP1 (50%)", f"{sig.partial_tp1:,.2f}", "1R exit"))
        if sig.partial_tp2 > 0:
            cells.append(_ti_cell("TP2 (50%)", f"{sig.partial_tp2:,.2f}", sig.target_type or "ATR", bull=True))
        elif sig.target > 0:
            cells.append(_ti_cell("Target", f"{sig.target:,.2f}", sig.target_type or "ATR", bull=True))

        rr_display = (f"{sig.partial_rr_model:.2f}R*" if sig.partial_rr_model > 0
                      else f"{sig.risk_reward:.2f}×")
        cells.append(_ti_cell("R:R", rr_display, "partial TP model" if sig.partial_rr_model else ""))

        blocked = filter_result and not filter_result.allowed
        if blocked:
            trade_idea = html.Div([
                html.Span("⊗", style={"fontSize": "16px", "marginRight": "8px"}),
                filter_result.reason,
            ], className="nqb-no-trade", style={"marginTop": "10px"})
        else:
            trade_idea = html.Div([
                html.Div(f"{'LONG' if is_long else 'SHORT'} IDEA", className="nqb-ti-label"),
                html.Div(cells, className="nqb-ti-row"),
            ], className="nqb-trade-idea")

    # Indicator vote table
    vote_rows = []
    for v in sig.votes:
        pct = int(v.strength * 100)
        cls = v.direction.lower()
        vote_rows.append(html.Tr([
            html.Td(v.name.replace("_", " ").title(),
                    style={"fontFamily": "ui-monospace,monospace", "fontSize": "11px"}),
            html.Td(html.Span(f"{'▲' if v.direction=='BULL' else '▼' if v.direction=='BEAR' else '─'} {v.direction}",
                              style={"color": BULL if v.direction=="BULL" else BEAR if v.direction=="BEAR" else DIM,
                                     "fontSize": "11px"})),
            html.Td([
                html.Span(className=f"nqb-strength-bar", children=[
                    html.Span(className=f"nqb-strength-fill {cls}",
                              style={"width": f"{pct}%", "display": "block", "height": "100%"})
                ]),
                html.Span(f"{pct}%", style={"fontSize": "11px", "fontFamily": "ui-monospace,monospace",
                                             "color": DIM, "marginLeft": "6px"}),
            ], style={"display": "flex", "alignItems": "center"}),
            html.Td(v.note[:50] if v.note else "—",
                    style={"color": MUTED, "fontSize": "11px"}),
        ]))

    vote_table = html.Table([
        html.Thead(html.Tr([
            html.Th("Indicator"), html.Th("Vote"), html.Th("Strength"), html.Th("Note"),
        ])),
        html.Tbody(vote_rows),
    ], className="nqb-vote-table")

    body = html.Div([
        # Bull/bear bar
        html.Div([
            html.Div([
                html.Div(style={"display": "flex", "justifyContent": "space-between",
                                "marginBottom": "3px"}, children=[
                    html.Span(f"Bull {sig.bull_score:.1f}",
                              style={"color": BULL, "fontSize": "11px", "fontFamily": "ui-monospace,monospace"}),
                    html.Span(f"Bear {sig.bear_score:.1f}",
                              style={"color": BEAR, "fontSize": "11px", "fontFamily": "ui-monospace,monospace"}),
                ]),
                html.Div([
                    html.Div(style={"width": bull_w}, className="nqb-bb-bull"),
                    html.Div(style={"width": bear_w}, className="nqb-bb-bear"),
                ], className="nqb-bb-bar"),
            ], style={"marginBottom": "10px"}),
        ]),

        # Signal summary grid
        html.Div(ss_blocks, className="nqb-ss-grid", style={"marginBottom": "10px"}),

        # Trade idea
        trade_idea,

        # Warnings from filter
        *([html.Div(f"⚠ {w}", style={"color": WARN, "fontSize": "11px", "marginTop": "6px"})
           for w in (filter_result.warnings if filter_result else [])]),

        # Vote table
        html.Div(vote_table, style={"marginTop": "12px", "overflowX": "auto"}),
    ])

    return _panel(
        f"Signal · {tf['label']}" if (is_long or is_short) else "Signal Engine",
        body,
        subtitle=f"{tf_key.upper()} · confluence {max(sig.bull_score, sig.bear_score):.0f}/100",
    )


def _ss_block(label, val):
    if isinstance(val, str):
        val_el = html.Div(val, className="nqb-ss-val mono")
    else:
        val_el = html.Div(val, className="nqb-ss-val")
    return html.Div([
        html.Div(label, className="nqb-ss-label"),
        val_el,
    ], className="nqb-ss-block")


def _ti_cell(label, val, sub, bull=False, bear=False):
    val_color = BULL if bull else (BEAR if bear else TEXT)
    children = [
        html.Span(label, className="nqb-ti-cell-label"),
        html.Span(str(val) if isinstance(val, (int, float)) else val,
                  className="nqb-ti-cell-val",
                  style={"color": val_color}),
    ]
    if sub:
        children.append(html.Span(sub, className="nqb-ti-cell-sub"))
    return html.Div(children, className="nqb-ti-cell")


def _build_context_panel(context, filter_result, sess, sig):
    items = []

    if context:
        REGIME_TONES = {
            "TRENDING_BULL": ("bull", BULL),
            "TRENDING_BEAR": ("bear", BEAR),
            "RANGING":       ("info", INFO),
            "CHOPPY":        ("warn", WARN),
            "VOLATILE":      ("warn", WARN),
            "LOW_VOL":       ("",     DIM),
        }
        tone, col = REGIME_TONES.get(context.regime, ("", DIM))
        regime_label = context.regime.replace("_", " ")
        items.append(html.Div([
            html.Span(regime_label, className=f"nqb-regime",
                      style={"color": col, "borderColor": col,
                             "background": f"{col.replace('oklch','oklch').split(')')[0]} / .12)".replace("oklch(","oklch(")}),
            html.Span(f"  ADX {context.adx:.0f}  ·  ATR {context.atr_ratio:.2f}×",
                      style={"color": DIM, "fontSize": "11px", "marginLeft": "8px", "fontFamily": "ui-monospace,monospace"}),
        ], style={"marginBottom": "8px"}))
        items.append(html.Div(context.description, style={"color": DIM, "fontSize": "11px", "marginBottom": "8px"}))

    if filter_result and not filter_result.allowed:
        items.append(html.Div([
            html.Span("⊗", style={"marginRight": "8px"}),
            filter_result.reason,
        ], className="nqb-no-trade", style={"marginBottom": "8px"}))

    # Session tradeable status
    if not sess.get("tradeable") and "NEUTRAL" not in sig.signal:
        items.append(html.Div(
            f"⚠ {sess.get('name','Session')} — low-quality session, consider waiting",
            style={"color": WARN, "fontSize": "11px", "marginBottom": "4px"}
        ))

    if not items:
        return ""

    return _panel("Market Context", html.Div(items), subtitle="regime · filter status")


def _build_positions_panel(open_trades):
    if not open_trades:
        return ""

    rows = []
    for t in open_trades[:10]:
        direction = t.get("direction", "LONG")
        entry     = t.get("entry", 0)
        stop      = t.get("stop_price", 0)
        target    = t.get("target", 0)
        mfe       = t.get("max_favorable", 0) or 0
        mae       = t.get("max_adverse",   0) or 0
        grade     = t.get("grade", "")
        rows.append(html.Tr([
            html.Td(_grade_badge(grade)),
            html.Td(html.Span(direction,
                              className=f"nqb-dir {'long' if direction=='LONG' else 'short'}",
                              style={"fontSize": "11px"})),
            html.Td(f"{entry:,.2f}",  className="num mono", style={"color": DIM}),
            html.Td(f"{stop:,.2f}",   className="num mono", style={"color": BEAR}),
            html.Td(f"{target:,.2f}", className="num mono", style={"color": BULL}),
            html.Td(f"+{mfe:.0f} / −{mae:.0f}", className="num mono",
                    style={"color": DIM, "fontSize": "11px"}),
        ]))

    table = html.Table([
        html.Thead(html.Tr([
            html.Th("Grade"), html.Th("Dir"), html.Th("Entry"), html.Th("Stop"),
            html.Th("Target"), html.Th("MFE/MAE pts"),
        ])),
        html.Tbody(rows),
    ], className="nqb-vote-table")

    return _panel("Open Positions", table,
                  subtitle=f"{len(open_trades)} active paper trades")


# ── Chart ─────────────────────────────────────────────────────────────────────

def _build_chart(df: pd.DataFrame, sig, tf_key: str) -> go.Figure:
    display_df = df.iloc[-120:].copy()
    xs = display_df.index

    fig = make_subplots(rows=2, cols=1, shared_xaxes=True,
                        row_heights=[0.82, 0.18], vertical_spacing=0.01)

    fig.add_trace(go.Candlestick(
        x=xs, open=display_df["open"], high=display_df["high"],
        low=display_df["low"], close=display_df["close"],
        increasing_line_color=BULL, decreasing_line_color=BEAR,
        increasing_fillcolor=BULL, decreasing_fillcolor=BEAR,
        name="NQ", line=dict(width=1),
    ), row=1, col=1)

    bar_colors = [
        f"rgba(52,211,153,{0.5 if c>=o else 0.15})" if c>=o
        else f"rgba(251,113,133,{0.5 if c<o else 0.15})"
        for c, o in zip(display_df["close"], display_df["open"])
    ]
    fig.add_trace(go.Bar(x=xs, y=display_df["volume"],
                         marker_color=bar_colors, showlegend=False), row=2, col=1)

    sh, sl = liq.swing_points(display_df, left=5, right=5)
    if not sh.empty:
        fig.add_trace(go.Scatter(x=sh.index, y=sh["level"] * 1.00025, mode="markers",
                                  marker=dict(symbol="triangle-down", color=BEAR, size=7, opacity=.8),
                                  showlegend=False, hovertemplate="SH %{y:,.1f}<extra></extra>"),
                      row=1, col=1)
    if not sl.empty:
        fig.add_trace(go.Scatter(x=sl.index, y=sl["level"] * 0.99975, mode="markers",
                                  marker=dict(symbol="triangle-up", color=BULL, size=7, opacity=.8),
                                  showlegend=False, hovertemplate="SL %{y:,.1f}<extra></extra>"),
                      row=1, col=1)

    eq_lvls = liq.equal_levels(sh, sl)
    eq_near = sorted(eq_lvls, key=lambda e: abs(e["level"] - sig.price))[:6]
    for eq in eq_near:
        is_high = eq["kind"] == "EQH"
        color   = "rgba(251,113,133,.45)" if is_high else "rgba(52,211,153,.45)"
        fig.add_hline(y=eq["level"], line=dict(color=color, width=1, dash="dot"),
                       annotation_text=eq["kind"],
                       annotation_font_color=BEAR if is_high else BULL,
                       annotation_font_size=9, annotation_xanchor="left", row=1, col=1)

    for ob in liq.order_blocks(display_df):
        is_bull = ob["kind"] == "bull_ob"
        fig.add_hrect(
            y0=ob["bottom"], y1=ob["top"],
            fillcolor="rgba(52,211,153,.08)" if is_bull else "rgba(251,113,133,.08)",
            line=dict(color="rgba(52,211,153,.4)" if is_bull else "rgba(251,113,133,.4)", width=1),
            annotation_text="OB ▲" if is_bull else "OB ▼",
            annotation_font_color=BULL if is_bull else BEAR,
            annotation_font_size=9, annotation_xanchor="left", row=1, col=1,
        )

    vp = liq.volume_profile(display_df, bins=36)
    max_vol = vp["volume"].max()
    p_range = display_df["high"].max() - display_df["low"].min()
    bin_half = p_range / (2 * len(vp))
    hvn_q = vp["volume"].quantile(0.80)
    if max_vol > 0:
        for _, row_vp in vp.iterrows():
            norm = row_vp["volume"] / max_vol
            fig.add_shape(
                type="rect", xref="paper", yref="y1",
                x0=1.0 - norm * 0.07, x1=1.0,
                y0=row_vp["price_mid"] - bin_half, y1=row_vp["price_mid"] + bin_half,
                fillcolor="rgba(52,211,153,.45)" if row_vp["volume"] >= hvn_q else "rgba(40,48,60,.5)",
                line_width=0,
            )

    if sig.stop_loss and sig.target and "NEUTRAL" not in sig.signal:
        for y_val, color, label in [
            (sig.price,     INFO,  f"Entry  {sig.price:,.1f}"),
            (sig.stop_loss, BEAR,  f"Stop  {sig.stop_loss:,.1f}"),
            (sig.target,    BULL,  f"Target  {sig.target:,.1f}"),
        ]:
            fig.add_hline(y=y_val,
                           line=dict(color=color, width=1.5,
                                     dash="solid" if y_val == sig.price else "dash"),
                           annotation_text=label,
                           annotation_font_color=color, annotation_font_size=10,
                           annotation_xanchor="right", row=1, col=1)
        if sig.partial_tp1 > 0:
            fig.add_hline(y=sig.partial_tp1,
                           line=dict(color=WARN, width=1, dash="dot"),
                           annotation_text=f"TP1  {sig.partial_tp1:,.1f}",
                           annotation_font_color=WARN, annotation_font_size=9,
                           annotation_xanchor="right", row=1, col=1)
        fig.add_hrect(y0=min(sig.price, sig.stop_loss), y1=max(sig.price, sig.stop_loss),
                       fillcolor="rgba(251,113,133,.06)", line_width=0, row=1, col=1)
        fig.add_hrect(y0=min(sig.price, sig.target), y1=max(sig.price, sig.target),
                       fillcolor="rgba(52,211,153,.06)", line_width=0, row=1, col=1)

    axis_c = dict(gridcolor="rgba(30,41,59,.8)", zerolinecolor="rgba(30,41,59,.8)",
                  tickfont=dict(size=10, color=DIM), showline=False, zeroline=False)
    fig.update_layout(
        paper_bgcolor=BG_1, plot_bgcolor=BG_2,
        font=dict(color=TEXT, family="-apple-system, BlinkMacSystemFont, 'Inter', sans-serif"),
        margin=dict(l=0, r=0, t=0, b=0),
        xaxis_rangeslider_visible=False,
        showlegend=False,
        hovermode="x unified",
        hoverlabel=dict(bgcolor=BG_2, font_size=11, font_color=TEXT, bordercolor=LINE_S),
        xaxis=dict(**axis_c, showspikes=True, spikecolor=DIM, spikethickness=1, spikedash="dot"),
        yaxis=dict(**axis_c, side="right", tickformat=",.0f"),
        xaxis2=dict(**axis_c),
        yaxis2=dict(**axis_c, showticklabels=False),
    )
    return fig


# ── Backtest callback ──────────────────────────────────────────────────────────

import backtest as bt_mod

@app.callback(
    [Output("bt-stats-row",    "children"),
     Output("bt-by-signal",    "children"),
     Output("bt-equity-chart", "figure"),
     Output("bt-trade-table",  "children")],
    Input("bt-run-btn", "n_clicks"),
    State("bt-tf-select", "value"),
    prevent_initial_call=True,
)
def run_backtest(_, tf_key):
    result = bt_mod.run(tf_key or "swing")

    if result.get("error") and not result["trades"]:
        return (html.Span(result["error"], style={"color": BEAR}),
                "", _empty_fig(result["error"]), "")

    stats = result.get("stats", {})
    if not stats:
        return (html.Span(result.get("error", "No trades"), style={"color": WARN}),
                "", _empty_fig("No completed trades"), "")

    wr_c = BULL if stats["win_rate"] >= 50 else BEAR
    net_usd = _usd_val(stats.get("net_r", 0))

    stats_row = [
        _kpi("Win Rate",      f"{stats['win_rate']}%",        tone="bull" if stats["win_rate"]>=50 else "bear"),
        _kpi("Avg R:R",       f"{stats['avg_rr']}×",         tone="info"),
        _kpi("Profit Factor", str(stats["profit_factor"]),    tone="bull" if net_usd>0 else "bear"),
        _kpi("Max Drawdown",  _usd(stats["max_drawdown_r"],False), tone="bear"),
        _kpi("Net P&L",       _usd(stats["net_r"]),           tone="bull" if net_usd>0 else "bear"),
        _kpi("Trades",        str(stats["total_trades"])),
    ]

    by_sig = result.get("by_signal", {})
    sig_rows = [html.Tr([
        html.Td(sn, style={"padding": "5px 10px", "fontSize": "12px"}),
        html.Td(str(d["trades"]), style={"padding": "5px 10px", "fontSize": "12px",
                                          "textAlign": "right", "color": DIM}),
        html.Td(f"{d['win_rate']}%", style={"padding": "5px 10px", "fontSize": "12px",
                                              "textAlign": "right",
                                              "color": BULL if d["win_rate"]>=50 else BEAR}),
    ]) for sn, d in by_sig.items()]
    by_sig_table = html.Table([
        html.Thead(html.Tr([
            html.Th("Signal",   style={"padding": "5px 10px", "color": MUTED, "fontSize": "10px",
                                       "textTransform": "uppercase"}),
            html.Th("Trades",   style={"padding": "5px 10px", "color": MUTED, "fontSize": "10px",
                                       "textAlign": "right"}),
            html.Th("Win Rate", style={"padding": "5px 10px", "color": MUTED, "fontSize": "10px",
                                       "textAlign": "right"}),
        ])),
        html.Tbody(sig_rows),
    ], style={"borderCollapse": "collapse", "backgroundColor": BG_1,
              "border": f"1px solid {LINE}", "borderRadius": "6px"}) if sig_rows else ""

    curve = result.get("equity_curve", [])
    if curve:
        cumulative = []
        running = 0
        for r in curve:
            running += r
            cumulative.append(running * BASE_RISK_USD)
        colors = [BULL if v >= 0 else BEAR for v in cumulative]
        eq_fig = go.Figure(go.Scatter(
            y=cumulative, mode="lines+markers",
            line=dict(color=INFO, width=2),
            marker=dict(size=4, color=colors),
            hovertemplate="Trade %{x+1}: $%{y:,.0f}<extra></extra>",
        ))
        eq_fig.add_hline(y=0, line=dict(color=LINE_S, width=1, dash="dot"))
        eq_fig.update_layout(
            paper_bgcolor=BG_1, plot_bgcolor=BG_2,
            font=dict(color=TEXT), margin=dict(l=0, r=0, t=24, b=0),
            title=dict(text="Equity Curve (cumulative P&L in $)", font=dict(size=11, color=DIM)),
            xaxis=dict(gridcolor=LINE, tickfont=dict(color=DIM), zeroline=False),
            yaxis=dict(gridcolor=LINE, tickfont=dict(color=DIM), zeroline=False, tickprefix="$"),
        )
    else:
        eq_fig = _empty_fig("No equity data")

    trades = result.get("trades", [])
    if trades:
        for t in trades:
            if "pnl_r" in t and t["pnl_r"] is not None:
                t["pnl_$"] = f"{'+'if t['pnl_r']>=0 else ''}${t['pnl_r']*BASE_RISK_USD:,.0f}"
        trade_table = dash_table.DataTable(
            data=trades,
            columns=[{"name": c.upper(), "id": c}
                     for c in ["time", "signal", "entry", "stop", "target", "rr", "outcome", "pnl_$"]],
            style_table={"overflowX": "auto"},
            style_header={"backgroundColor": BG_2, "color": MUTED, "fontWeight": "600",
                          "fontSize": "10px", "border": f"1px solid {LINE}",
                          "textTransform": "uppercase"},
            style_cell={"backgroundColor": BG_1, "color": TEXT, "fontSize": "12px",
                        "border": f"1px solid {LINE}", "padding": "6px 10px"},
            style_data_conditional=[
                {"if": {"filter_query": "{outcome} = WIN"},  "color": BULL},
                {"if": {"filter_query": "{outcome} = LOSS"}, "color": BEAR},
            ],
            page_size=20,
        )
    else:
        trade_table = html.Span("No trades.", style={"color": MUTED})

    return stats_row, by_sig_table, eq_fig, trade_table


# ── Risk calculator callback ───────────────────────────────────────────────────

@app.callback(
    Output("rc-results", "children"),
    [Input("rc-account",       "value"),
     Input("rc-risk-pct",      "value"),
     Input("rc-max-loss",      "value"),
     Input("rc-entry",         "value"),
     Input("rc-stop",          "value"),
     Input("rc-contract-type", "value")],
)
def compute_risk(account, risk_pct, max_loss, entry, stop, contract_type):
    try:
        account   = float(account  or cfg.DEFAULT_ACCOUNT_SIZE)
        risk_pct  = float(risk_pct or cfg.DEFAULT_RISK_PCT)
        max_loss  = float(max_loss or cfg.DEFAULT_MAX_LOSS)
        entry     = float(entry or 0)
        stop      = float(stop  or 0)
    except (TypeError, ValueError):
        return html.Span("Enter valid numbers", style={"color": MUTED})

    pt_val       = cfg.NQ_POINT_VALUE if contract_type == "NQ" else cfg.MNQ_POINT_VALUE
    risk_from_pct= account * risk_pct / 100
    dollar_risk  = min(risk_from_pct, max_loss)

    stop_pts = contracts = actual_risk = profit_25r = profit_3r = 0
    if entry > 0 and stop > 0 and entry != stop:
        stop_pts     = abs(entry - stop)
        dollar_per_c = stop_pts * pt_val
        contracts    = max(1, int(dollar_risk / dollar_per_c)) if dollar_per_c > 0 else 0
        actual_risk  = contracts * dollar_per_c
        profit_25r   = actual_risk * 2.5
        profit_3r    = actual_risk * 3.0

    def _row(label, val, color=TEXT2):
        return html.Div(style={"display": "flex", "justifyContent": "space-between",
                                "padding": "5px 0", "borderBottom": f"1px solid {LINE}"}, children=[
            html.Span(label, style={"color": MUTED, "fontSize": "12px"}),
            html.Span(val,   style={"color": color, "fontSize": "13px",
                                    "fontFamily": "ui-monospace,monospace", "fontWeight": "600"}),
        ])

    return html.Div(style={"backgroundColor": BG_2, "border": f"1px solid {LINE}",
                            "borderRadius": "6px", "padding": "14px 16px"}, children=[
        _row("Max $ Risk",           f"${dollar_risk:,.0f}",    WARN),
        _row("Stop Distance",        f"{stop_pts:.2f} pts"  if stop_pts else "—", DIM),
        _row(f"Contracts ({contract_type})", str(contracts) if contracts else "—",
             BULL if contracts else DIM),
        _row("Actual $ Risk",        f"${actual_risk:,.0f}" if actual_risk else "—", BEAR),
        _row("2.5R Target Profit",   f"${profit_25r:,.0f}"  if profit_25r else "—", BULL),
        _row("3R Target Profit",     f"${profit_3r:,.0f}"   if profit_3r  else "—", BULL),
    ])


# ── Journal callbacks ──────────────────────────────────────────────────────────

@app.callback(
    [Output("jrn-table-container", "children"),
     Output("jrn-store",           "data")],
    Input("jrn-refresh-btn", "n_clicks"),
)
def load_journal(_):
    rows = journal_mod.load_journal()
    if not rows:
        return html.Span("No trades logged yet. A/A+ signals are auto-logged.",
                         style={"color": MUTED, "fontSize": "13px"}), []
    table = dash_table.DataTable(
        id="jrn-datatable", data=rows,
        columns=[{"name": c.replace("_"," ").upper(), "id": c,
                  "editable": c in ("outcome","pnl_pts")}
                 for c in journal_mod.FIELDS],
        style_table={"overflowX": "auto"},
        style_header={"backgroundColor": BG_2, "color": MUTED, "fontWeight": "600",
                       "fontSize": "10px", "border": f"1px solid {LINE}",
                       "textTransform": "uppercase"},
        style_cell={"backgroundColor": BG_1, "color": TEXT, "fontSize": "12px",
                    "border": f"1px solid {LINE}", "padding": "6px 10px",
                    "maxWidth": "220px", "overflow": "hidden", "textOverflow": "ellipsis"},
        style_data_conditional=[
            {"if": {"filter_query": "{outcome} = WIN"},  "color": BULL},
            {"if": {"filter_query": "{outcome} = LOSS"}, "color": BEAR},
            {"if": {"column_id": "outcome"}, "backgroundColor": BG_3, "border": f"1px solid {INFO}"},
            {"if": {"column_id": "pnl_pts"}, "backgroundColor": BG_3, "border": f"1px solid {INFO}"},
        ],
        editable=True, page_size=25, sort_action="native", filter_action="native",
    )
    return table, rows


@app.callback(Output("jrn-store", "data", allow_duplicate=True),
              Input("jrn-datatable", "data"), prevent_initial_call=True)
def save_journal_edits(data):
    if data: journal_mod.save_journal(data)
    return data


@app.callback(Output("jrn-download", "data"),
              Input("jrn-export-btn", "n_clicks"),
              State("jrn-store", "data"), prevent_initial_call=True)
def export_journal(_, data):
    if not data: return None
    df_out = pd.DataFrame(data, columns=journal_mod.FIELDS)
    return dcc.send_data_frame(df_out.to_csv, "nqb_trade_journal.csv", index=False)


# ── Analytics callbacks ────────────────────────────────────────────────────────

def _wr_table(rows, key):
    if not rows:
        return html.Span("No data yet.", style={"color": MUTED, "fontSize": "12px"})
    return dash_table.DataTable(
        data=rows,
        columns=[{"name": c.replace("_"," ").upper(), "id": c}
                 for c in [key, "trades", "win_rate", "avg_rr"]],
        style_table={"overflowX": "auto"},
        style_header={"backgroundColor": BG_2, "color": MUTED, "fontWeight": "600",
                       "fontSize": "10px", "border": f"1px solid {LINE}", "textTransform": "uppercase"},
        style_cell={"backgroundColor": BG_1, "color": TEXT, "fontSize": "11px",
                    "border": f"1px solid {LINE}", "padding": "4px 8px"},
        style_data_conditional=[
            {"if": {"filter_query": "{win_rate} >= 55"}, "color": BULL},
            {"if": {"filter_query": "{win_rate} < 45"},  "color": BEAR},
        ],
        sort_action="native", page_size=8,
    )


@app.callback(
    [Output("ana-summary-row",    "children"),
     Output("ana-tf-table",       "children"),
     Output("ana-sess-table",     "children"),
     Output("ana-grade-table",    "children"),
     Output("ana-sigtype-table",  "children"),
     Output("ana-best-table",     "children"),
     Output("ana-worst-table",    "children"),
     Output("ana-weight-chart",   "figure"),
     Output("ana-factor-table",   "children"),
     Output("ana-weight-history", "children"),
     Output("ana-status",         "children")],
    [Input("ana-refresh-btn",   "n_clicks"),
     Input("ana-weight-btn",    "n_clicks"),
     Input("ana-ml-train-btn",  "n_clicks")],
    prevent_initial_call=False,
)
def refresh_analytics(n_r, n_w, n_ml):
    ctx = callback_context
    status_msg = ""

    if ctx.triggered and "ana-weight-btn" in ctx.triggered[0]["prop_id"]:
        try:
            res = learn_mod.run_walk_forward(force=True)
            status_msg = (f"Weights updated · test WR: {res.get('test_win_rate',0)}%"
                          if res.get("status") == "updated" else res.get("reason","—"))
        except Exception as e:
            status_msg = f"Error: {e}"

    if ctx.triggered and "ana-ml-train-btn" in ctx.triggered[0]["prop_id"]:
        try:
            res = ml_model.train_and_save()
            status_msg = (f"ML ({res.get('model_type','')}) trained on {res.get('n_train',0)} trades"
                          if res.get("status") == "trained" else res.get("reason","—"))
        except Exception as e:
            status_msg = f"ML error: {e}"

    trades = db_mod.get_completed_trades()
    stats  = ana_mod.overall_stats(trades)

    net_usd = _usd_val(stats.get("net_r"))
    exp_usd = _usd_val(stats.get("expectancy"))

    summary_row = []
    if stats:
        summary_row = [
            _kpi("Total Trades",   str(stats.get("total",0))),
            _kpi("Win Rate",       f"{stats.get('win_rate',0)}%",
                 tone="bull" if stats.get("win_rate",0)>=50 else "bear"),
            _kpi("Net P&L",        _usd(stats.get("net_r")),
                 tone="bull" if net_usd>=0 else "bear"),
            _kpi("Expectancy",     _usd(stats.get("expectancy")) if stats.get("expectancy") is not None else "—",
                 tone="bull" if exp_usd>=0 else "bear"),
            _kpi("Profit Factor",  str(stats.get("profit_factor") or "—")),
            _kpi("Max Drawdown",   _usd(stats.get("max_drawdown_r",0), signed=False), tone="bear"),
        ]
    else:
        summary_row = [html.Span("No completed trades yet.",
                                  style={"color": MUTED, "fontSize": "13px"})]

    tf_table    = _wr_table(ana_mod.win_rate_table("timeframe",   trades), "timeframe")
    sess_table  = _wr_table(ana_mod.win_rate_table("session",     trades), "session")
    grade_table = _wr_table(ana_mod.win_rate_table("grade",       trades), "grade")
    stype_table = _wr_table(ana_mod.win_rate_table("signal_type", trades), "signal_type")

    best_rows  = ana_mod.best_setups(trades,  top_n=6)
    worst_rows = ana_mod.worst_setups(trades, top_n=6)

    def _setup_table(rows, col):
        if not rows: return html.Span("Need more data.", style={"color": MUTED, "fontSize": "12px"})
        return dash_table.DataTable(
            data=rows,
            columns=[{"name": c.upper(), "id": c} for c in ["setup","trades","win_rate","avg_r"]],
            style_table={"overflowX": "auto"},
            style_header={"backgroundColor": BG_2, "color": MUTED, "fontWeight": "600",
                           "fontSize": "10px", "border": f"1px solid {LINE}", "textTransform": "uppercase"},
            style_cell={"backgroundColor": BG_1, "color": TEXT, "fontSize": "11px",
                        "border": f"1px solid {LINE}", "padding": "4px 8px",
                        "maxWidth": "260px", "overflow": "hidden", "textOverflow": "ellipsis"},
            style_data_conditional=[{"if": {"column_id": "win_rate"}, "color": col}],
            page_size=6,
        )

    best_table  = _setup_table(best_rows,  BULL)
    worst_table = _setup_table(worst_rows, BEAR)

    contrib    = ana_mod.indicator_contribution(trades)
    weight_fig = _empty_fig("No trade data")
    if contrib:
        names  = list(contrib.keys())
        scores = [contrib[n].get("contribution_score",0)*100 for n in names]
        colors = [BULL if s>=0 else BEAR for s in scores]
        cw     = learn_mod.get_current_weights()
        weight_fig = go.Figure(go.Bar(
            x=names, y=scores, marker_color=colors,
            text=[f"w={cw.get(n,0):.3f}" for n in names], textposition="outside",
            hovertemplate="%{x}: %{y:.1f}%<extra></extra>",
        ))
        weight_fig.add_hline(y=0, line=dict(color=LINE_S, width=1))
        weight_fig.update_layout(
            paper_bgcolor=BG_1, plot_bgcolor=BG_2, font=dict(color=TEXT),
            margin=dict(l=0, r=0, t=24, b=0),
            title=dict(text="Contribution above chance & current weight",
                       font=dict(size=11, color=DIM)),
            xaxis=dict(gridcolor=LINE, tickfont=dict(color=DIM, size=10)),
            yaxis=dict(gridcolor=LINE, tickfont=dict(color=DIM), title="% above chance"),
        )

    factors    = ana_mod.factor_correlation(trades)
    factor_table = html.Span("Need more data.", style={"color": MUTED, "fontSize": "12px"})
    if factors:
        factor_table = dash_table.DataTable(
            data=factors[:15],
            columns=[{"name": c.upper(), "id": c} for c in ["reason","appearances","win_rate"]],
            style_table={"overflowX": "auto"},
            style_header={"backgroundColor": BG_2, "color": MUTED, "fontWeight": "600",
                           "fontSize": "10px", "border": f"1px solid {LINE}", "textTransform": "uppercase"},
            style_cell={"backgroundColor": BG_1, "color": TEXT, "fontSize": "11px",
                        "border": f"1px solid {LINE}", "padding": "4px 8px",
                        "maxWidth": "280px", "overflow": "hidden", "textOverflow": "ellipsis"},
            style_data_conditional=[
                {"if": {"filter_query": "{win_rate} >= 55"}, "color": BULL},
                {"if": {"filter_query": "{win_rate} < 45"},  "color": BEAR},
            ],
            page_size=10,
        )

    wh = learn_mod.weight_history_table()
    wh_table = html.Span("No weight updates yet.", style={"color": MUTED, "fontSize": "12px"})
    if wh:
        wh_table = dash_table.DataTable(
            data=wh,
            columns=[{"name": c.upper(), "id": c}
                     for c in ["indicator","initial","current","total_change","last_test_wr","updates"]],
            style_table={"overflowX": "auto"},
            style_header={"backgroundColor": BG_2, "color": MUTED, "fontWeight": "600",
                           "fontSize": "10px", "border": f"1px solid {LINE}", "textTransform": "uppercase"},
            style_cell={"backgroundColor": BG_1, "color": TEXT, "fontSize": "11px",
                        "border": f"1px solid {LINE}", "padding": "4px 8px"},
            style_data_conditional=[
                {"if": {"filter_query": "{total_change} > 0"}, "color": BULL},
                {"if": {"filter_query": "{total_change} < 0"}, "color": BEAR},
            ],
        )

    return (summary_row, tf_table, sess_table, grade_table, stype_table,
            best_table, worst_table, weight_fig, factor_table, wh_table, status_msg)


# ── Paper trading callbacks ────────────────────────────────────────────────────

def _trade_table(rows, cols):
    if not rows: return html.Span("No trades.", style={"color": MUTED, "fontSize": "12px"})
    return dash_table.DataTable(
        data=rows, columns=[{"name": c.replace("_"," ").upper(), "id": c} for c in cols],
        style_table={"overflowX": "auto"},
        style_header={"backgroundColor": BG_2, "color": MUTED, "fontWeight": "600",
                       "fontSize": "10px", "border": f"1px solid {LINE}", "textTransform": "uppercase"},
        style_cell={"backgroundColor": BG_1, "color": TEXT, "fontSize": "11px",
                    "border": f"1px solid {LINE}", "padding": "4px 8px",
                    "maxWidth": "160px", "overflow": "hidden", "textOverflow": "ellipsis"},
        style_data_conditional=[
            {"if": {"filter_query": "{outcome} = WIN"},  "color": BULL},
            {"if": {"filter_query": "{outcome} = LOSS"}, "color": BEAR},
        ],
        page_size=15, sort_action="native",
    )


@app.callback(
    [Output("pt-enabled",     "data"),
     Output("pt-toggle-btn",  "children"),
     Output("pt-toggle-btn",  "className")],
    Input("pt-toggle-btn", "n_clicks"),
    State("pt-enabled",    "data"),
    prevent_initial_call=True,
)
def toggle_paper(_, enabled):
    new = not bool(enabled)
    if new:
        pt_mod.enable()
        return new, "■ Disable Paper Trading", "nqb-btn nqb-btn-ghost"
    else:
        pt_mod.disable()
        return new, "▶ Enable Paper Trading",  "nqb-btn nqb-btn-primary"


@app.callback(
    [Output("pt-summary-row",   "children"),
     Output("pt-status-badge",  "children"),
     Output("pt-open-table",    "children"),
     Output("pt-closed-table",  "children")],
    [Input("pt-refresh-btn", "n_clicks"),
     Input("pt-poll",        "n_intervals")],
    State("pt-enabled", "data"),
)
def refresh_paper(_, __, pt_enabled):
    try: pt_mod.refresh_open_trades()
    except Exception: pass

    summary = pt_mod.paper_trade_summary()
    wr = summary.get("win_rate") or 0
    net_r = summary.get("net_r") or 0

    mode_badge = html.Span(
        "PAPER ON" if pt_enabled else "PAPER OFF",
        style={"color": BULL if pt_enabled else MUTED,
               "background": "oklch(0.78 0.16 152 / .12)" if pt_enabled else BG_2,
               "border": f"1px solid {'var(--bull)' if pt_enabled else 'var(--line)'}",
               "borderRadius": "999px", "padding": "3px 10px",
               "fontSize": "12px", "fontWeight": "600"},
    )

    summary_row = [
        _kpi("Open",         str(summary.get("open",0))),
        _kpi("Closed",       str(summary.get("closed",0))),
        _kpi("Win Rate",     f"{wr}%" if wr else "—",  tone="bull" if wr>=50 else "bear"),
        _kpi("Net P&L",      _usd(net_r),               tone="bull" if net_r>=0 else "bear"),
        _kpi("Profit Factor",str(summary.get("profit_factor") or "—")),
    ]

    open_cols   = ["timestamp","timeframe","direction","grade","entry","stop_price","target",
                   "max_favorable","max_adverse"]
    closed_cols = ["timestamp","timeframe","direction","grade","entry","stop_price","target",
                   "outcome","pnl_pts","pnl_r"]

    open_rows   = pt_mod.get_open_paper_trades()
    closed_rows = pt_mod.get_closed_paper_trades(limit=50)

    # Add dollar P&L column to closed
    for t in closed_rows:
        r = t.get("pnl_r")
        t["pnl_$"] = _usd(r) if r is not None else "—"

    return (summary_row, mode_badge,
            _trade_table(open_rows,   open_cols),
            _trade_table(closed_rows, ["timestamp","timeframe","direction","grade",
                                        "entry","stop_price","target","outcome","pnl_$"]))


@app.callback(
    [Output("pt-report-container", "children"),
     Output("pt-report-container", "style")],
    Input("pt-report-btn", "n_clicks"),
    prevent_initial_call=True,
)
def show_weekly_report(_):
    text = ana_mod.weekly_report(paper_only=True)
    style = {"backgroundColor": BG_1, "border": f"1px solid {LINE}",
             "borderRadius": "6px", "padding": "16px", "display": "block", "marginTop": "12px"}
    return html.Pre(text, style={"color": TEXT2, "fontSize": "12px",
                                  "lineHeight": "1.8", "margin": 0, "whiteSpace": "pre-wrap"}), style


# ── Profitability Report callback ──────────────────────────────────────────────

def _exp_table(rows, key):
    if not rows:
        return html.Span("No data yet.", style={"color": MUTED, "fontSize": "12px"})
    # Convert R to $ for display
    disp = []
    for r in rows:
        d = dict(r)
        d["exp_$"]      = _usd(r.get("expectancy"))
        d["avg_win_$"]  = _usd(r.get("avg_win_r"),  signed=False)
        d["avg_loss_$"] = _usd(r.get("avg_loss_r"), signed=False)
        disp.append(d)
    return dash_table.DataTable(
        data=disp,
        columns=[{"name": c.replace("_"," ").upper(), "id": c}
                 for c in [key, "trades", "win_rate", "avg_win_$", "avg_loss_$", "exp_$"]],
        style_table={"overflowX": "auto"},
        style_header={"backgroundColor": BG_2, "color": MUTED, "fontWeight": "600",
                       "fontSize": "10px", "border": f"1px solid {LINE}", "textTransform": "uppercase"},
        style_cell={"backgroundColor": BG_1, "color": TEXT, "fontSize": "11px",
                    "border": f"1px solid {LINE}", "padding": "4px 8px"},
        style_data_conditional=[
            {"if": {"filter_query": '{exp_$} contains "+"'}, "color": BULL},
            {"if": {"filter_query": '{exp_$} contains "−"'}, "color": BEAR},
        ],
        sort_action="native", page_size=8,
    )


@app.callback(
    [Output("prf-summary-row",    "children"),
     Output("prf-best-sess",      "children"),
     Output("prf-worst-sess",     "children"),
     Output("prf-best-setup",     "children"),
     Output("prf-worst-setup",    "children"),
     Output("prf-exp-sess",       "children"),
     Output("prf-exp-tf",         "children"),
     Output("prf-exp-grade",      "children"),
     Output("prf-exp-stype",      "children"),
     Output("prf-recommendations","children")],
    [Input("prf-refresh-btn", "n_clicks"),
     Input("prf-mode",        "value")],
    prevent_initial_call=False,
)
def refresh_profit(_, mode):
    all_trades = db_mod.get_completed_trades(paper_only=False)
    if mode == "live":
        trades = [t for t in all_trades if not t.get("paper_trade")]
    elif mode == "paper":
        trades = [t for t in all_trades if t.get("paper_trade")]
    else:
        trades = all_trades

    stats   = ana_mod.overall_stats(trades)
    no_data = html.Span("No completed trades yet.", style={"color": MUTED, "fontSize": "13px"})

    if not trades or not stats:
        empty = [no_data]
        return empty, no_data, no_data, no_data, no_data, no_data, no_data, no_data, no_data, no_data

    net_usd  = _usd_val(stats.get("net_r"))
    exp_usd  = _usd_val(stats.get("expectancy"))
    dd_usd   = _usd_val(stats.get("max_drawdown_r", 0))
    avg_usd  = _usd_val(stats.get("avg_r_per_trade", 0))
    pf       = stats.get("profit_factor")
    wr       = stats.get("win_rate", 0)

    summary_row = [
        _kpi("Win Rate",     f"{wr:.1f}%",             tone="bull" if wr>=50 else "bear", big=True),
        _kpi("Net P&L",      _usd(stats.get("net_r")), tone="bull" if net_usd>=0 else "bear", big=True),
        _kpi("Profit Factor",str(pf) if pf else "—",   tone="bull" if (pf or 0)>=1 else "bear"),
        _kpi("Expectancy",   _usd(stats.get("expectancy")) if stats.get("expectancy") is not None else "—",
             sub="per trade", tone="bull" if exp_usd>=0 else "bear"),
        _kpi("Avg P&L/Trade", _usd(stats.get("avg_r_per_trade",0)),
             tone="bull" if avg_usd>=0 else "bear"),
        _kpi("Max Drawdown", _usd(stats.get("max_drawdown_r",0), signed=False),
             sub="peak-to-trough", tone="bear"),
        _kpi("Total Trades", str(stats.get("total",0))),
    ]

    sess_rows = ana_mod.win_rate_table("session", trades)

    def _mini(rows, key, desc=True):
        if not rows: return html.Span("Not enough data.", style={"color": MUTED, "fontSize": "12px"})
        display = sorted(rows, key=lambda r: r["win_rate"], reverse=desc)[:5]
        return dash_table.DataTable(
            data=display,
            columns=[{"name": c.replace("_"," ").upper(), "id": c}
                     for c in [key, "trades", "win_rate", "avg_rr"]],
            style_table={"overflowX": "auto"},
            style_header={"backgroundColor": BG_2, "color": MUTED, "fontWeight": "600",
                           "fontSize": "10px", "border": f"1px solid {LINE}", "textTransform": "uppercase"},
            style_cell={"backgroundColor": BG_1, "color": TEXT, "fontSize": "11px",
                        "border": f"1px solid {LINE}", "padding": "4px 8px",
                        "maxWidth": "220px", "overflow": "hidden", "textOverflow": "ellipsis"},
            style_data_conditional=[
                {"if": {"filter_query": "{win_rate} >= 55"}, "color": BULL},
                {"if": {"filter_query": "{win_rate} < 45"},  "color": BEAR},
            ],
            page_size=5,
        )

    best_sess  = _mini(sess_rows, "session", desc=True)
    worst_sess = _mini(sess_rows, "session", desc=False)

    def _setup_mini(rows, col):
        if not rows: return html.Span("Not enough data.", style={"color": MUTED, "fontSize": "12px"})
        return dash_table.DataTable(
            data=rows,
            columns=[{"name": c.upper(), "id": c} for c in ["setup","trades","win_rate","avg_r"]],
            style_table={"overflowX": "auto"},
            style_header={"backgroundColor": BG_2, "color": MUTED, "fontWeight": "600",
                           "fontSize": "10px", "border": f"1px solid {LINE}", "textTransform": "uppercase"},
            style_cell={"backgroundColor": BG_1, "color": TEXT, "fontSize": "11px",
                        "border": f"1px solid {LINE}", "padding": "4px 8px",
                        "maxWidth": "280px", "overflow": "hidden", "textOverflow": "ellipsis"},
            style_data_conditional=[{"if": {"column_id": "win_rate"}, "color": col}],
            page_size=5,
        )

    best_setup  = _setup_mini(ana_mod.best_setups(trades,  5), BULL)
    worst_setup = _setup_mini(ana_mod.worst_setups(trades, 5), BEAR)

    exp_sess  = _exp_table(ana_mod.expectancy_by("session",     trades), "session")
    exp_tf    = _exp_table(ana_mod.expectancy_by("timeframe",   trades), "timeframe")
    exp_grade = _exp_table(ana_mod.expectancy_by("grade",       trades), "grade")
    exp_stype = _exp_table(ana_mod.expectancy_by("signal_type", trades), "signal_type")

    recs = []
    if sess_rows:
        ws = min(sess_rows, key=lambda r: r["win_rate"])
        bs = max(sess_rows, key=lambda r: r["win_rate"])
        if ws["win_rate"] < 40:
            recs.append(f"Avoid {ws['session']} — {ws['win_rate']}% WR ({ws['trades']} trades). Consider filtering it out.")
        if bs["win_rate"] >= 60:
            recs.append(f"Focus on {bs['session']} — strongest at {bs['win_rate']}% WR.")
    for row in ana_mod.expectancy_by("grade", trades):
        exp_v = row.get("expectancy", 0)
        if exp_v < 0:
            recs.append(f"Grade {row['grade']} has NEGATIVE expectancy ({_usd(exp_v)}/trade) — raise filters or disable.")
        elif exp_v > 0.3:
            recs.append(f"Grade {row['grade']} is your best edge ({_usd(exp_v)}/trade) — consider larger size.")
    if (stats.get("avg_mae_pts",0) or 0) > (stats.get("avg_mfe_pts",0) or 0):
        recs.append("Avg MAE > Avg MFE — stops may be too tight or entries are chasing. Wait for deeper pullbacks.")
    if (pf or 0) < 1.0 and stats.get("total",0) >= 10:
        recs.append("Profit factor < 1.0 — losing more than winning in dollar terms. Focus on R:R ≥ 2.5 only.")
    if not recs:
        recs.append("Accumulate more completed trades for statistically meaningful recommendations.")

    rec_el = html.Div([
        html.Div(f"→  {r}", style={
            "color": WARN, "fontSize": "12px", "lineHeight": "2.0",
            "borderBottom": f"1px solid {LINE}", "padding": "4px 0",
        }) for r in recs
    ], style={"backgroundColor": BG_1, "border": f"1px solid {LINE}",
               "borderRadius": "6px", "padding": "12px 16px"})

    return (summary_row, best_sess, worst_sess, best_setup, worst_setup,
            exp_sess, exp_tf, exp_grade, exp_stype, rec_el)


# ── Entry point ────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    print("NQB  →  http://127.0.0.1:8050")
    app.run(debug=False, host="127.0.0.1", port=8050)
